"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Search, Filter } from "lucide-react"

interface Element {
  name: string
  symbol: string
  atomicNumber: number
  atomicMass: string
  category: string
  group: number
  period: number
  phaseAtSTP: string
  electronConfiguration: string
  summary: string
  discoveredBy: string
  discoveryYear: string
  source: string
  meltingPointC: number | null
  boilingPointC: number | null
  density: number | null
  electronegativity: number | null
  ionizationEnergy: number | null
}

const allElements: Element[] = [
  {
    name: "Hydrogen",
    symbol: "H",
    atomicNumber: 1,
    atomicMass: "1.008",
    category: "Reactive Nonmetal",
    group: 1,
    period: 1,
    phaseAtSTP: "Gas",
    electronConfiguration: "1s¹",
    summary: "Lightest element, most abundant in the universe, essential for water and organic compounds.",
    discoveredBy: "Henry Cavendish",
    discoveryYear: "1766",
    source: "From Greek 'hydro' (water) and 'genes' (forming)",
    meltingPointC: -259.16,
    boilingPointC: -252.87,
    density: 0.08988,
    electronegativity: 2.2,
    ionizationEnergy: 1312.0,
  },
  {
    name: "Helium",
    symbol: "He",
    atomicNumber: 2,
    atomicMass: "4.003",
    category: "Noble Gas",
    group: 18,
    period: 1,
    phaseAtSTP: "Gas",
    electronConfiguration: "1s²",
    summary: "Second lightest element, inert noble gas used in balloons and as a coolant.",
    discoveredBy: "Pierre Janssen",
    discoveryYear: "1868",
    source: "From Greek 'helios' (sun)",
    meltingPointC: -272.2,
    boilingPointC: -268.93,
    density: 0.1786,
    electronegativity: null,
    ionizationEnergy: 2372.3,
  },
  {
    name: "Lithium",
    symbol: "Li",
    atomicNumber: 3,
    atomicMass: "6.94",
    category: "Alkali Metal",
    group: 1,
    period: 2,
    phaseAtSTP: "Solid",
    electronConfiguration: "[He] 2s¹",
    summary: "Lightest metal, highly reactive, used in batteries and psychiatric medications.",
    discoveredBy: "Johan August Arfwedson",
    discoveryYear: "1817",
    source: "From Greek 'lithos' (stone)",
    meltingPointC: 180.5,
    boilingPointC: 1342,
    density: 0.534,
    electronegativity: 0.98,
    ionizationEnergy: 520.2,
  },
  {
    name: "Beryllium",
    symbol: "Be",
    atomicNumber: 4,
    atomicMass: "9.012",
    category: "Alkaline Earth Metal",
    group: 2,
    period: 2,
    phaseAtSTP: "Solid",
    electronConfiguration: "[He] 2s²",
    summary: "Light, strong metal used in aerospace and electronics applications.",
    discoveredBy: "Louis-Nicolas Vauquelin",
    discoveryYear: "1798",
    source: "From Greek 'beryllos' (beryl mineral)",
    meltingPointC: 1287,
    boilingPointC: 2469,
    density: 1.85,
    electronegativity: 1.57,
    ionizationEnergy: 899.5,
  },
  {
    name: "Boron",
    symbol: "B",
    atomicNumber: 5,
    atomicMass: "10.81",
    category: "Metalloid",
    group: 13,
    period: 2,
    phaseAtSTP: "Solid",
    electronConfiguration: "[He] 2s² 2p¹",
    summary: "Metalloid used in glass, ceramics, and as a neutron absorber in nuclear reactors.",
    discoveredBy: "Joseph-Louis Gay-Lussac",
    discoveryYear: "1808",
    source: "From Arabic 'buraq' (borax)",
    meltingPointC: 2075,
    boilingPointC: 4000,
    density: 2.34,
    electronegativity: 2.04,
    ionizationEnergy: 800.6,
  },
  {
    name: "Carbon",
    symbol: "C",
    atomicNumber: 6,
    atomicMass: "12.01",
    category: "Reactive Nonmetal",
    group: 14,
    period: 2,
    phaseAtSTP: "Solid",
    electronConfiguration: "[He] 2s² 2p²",
    summary: "Essential for all known life, forms diamonds and graphite, basis of organic chemistry.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'carbo' (coal)",
    meltingPointC: 3823,
    boilingPointC: 4827,
    density: 2.267,
    electronegativity: 2.55,
    ionizationEnergy: 1086.5,
  },
  {
    name: "Nitrogen",
    symbol: "N",
    atomicNumber: 7,
    atomicMass: "14.01",
    category: "Reactive Nonmetal",
    group: 15,
    period: 2,
    phaseAtSTP: "Gas",
    electronConfiguration: "[He] 2s² 2p³",
    summary: "Major component of air, essential for proteins and nucleic acids.",
    discoveredBy: "Daniel Rutherford",
    discoveryYear: "1772",
    source: "From Greek 'nitron' (soda) and 'genes' (forming)",
    meltingPointC: -210.0,
    boilingPointC: -195.8,
    density: 1.251,
    electronegativity: 3.04,
    ionizationEnergy: 1402.3,
  },
  {
    name: "Oxygen",
    symbol: "O",
    atomicNumber: 8,
    atomicMass: "16.00",
    category: "Reactive Nonmetal",
    group: 16,
    period: 2,
    phaseAtSTP: "Gas",
    electronConfiguration: "[He] 2s² 2p⁴",
    summary: "Essential for respiration, forms water and many organic compounds.",
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: "1772",
    source: "From Greek 'oxys' (sharp) and 'genes' (forming)",
    meltingPointC: -218.3,
    boilingPointC: -183.0,
    density: 1.429,
    electronegativity: 3.44,
    ionizationEnergy: 1313.9,
  },
  {
    name: "Fluorine",
    symbol: "F",
    atomicNumber: 9,
    atomicMass: "19.00",
    category: "Reactive Nonmetal",
    group: 17,
    period: 2,
    phaseAtSTP: "Gas",
    electronConfiguration: "[He] 2s² 2p⁵",
    summary: "Most electronegative element, highly reactive, used in refrigerants and toothpaste.",
    discoveredBy: "Henri Moissan",
    discoveryYear: "1886",
    source: "From Latin 'fluere' (to flow)",
    meltingPointC: -219.6,
    boilingPointC: -188.1,
    density: 1.696,
    electronegativity: 3.98,
    ionizationEnergy: 1681.0,
  },
  {
    name: "Neon",
    symbol: "Ne",
    atomicNumber: 10,
    atomicMass: "20.18",
    category: "Noble Gas",
    group: 18,
    period: 2,
    phaseAtSTP: "Gas",
    electronConfiguration: "[He] 2s² 2p⁶",
    summary: "Inert noble gas used in neon signs and lighting applications.",
    discoveredBy: "William Ramsay",
    discoveryYear: "1898",
    source: "From Greek 'neos' (new)",
    meltingPointC: -248.6,
    boilingPointC: -246.1,
    density: 0.9002,
    electronegativity: null,
    ionizationEnergy: 2080.7,
  },
  {
    name: "Sodium",
    symbol: "Na",
    atomicNumber: 11,
    atomicMass: "22.99",
    category: "Alkali Metal",
    group: 1,
    period: 3,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ne] 3s¹",
    summary: "Highly reactive metal, essential electrolyte in biological systems.",
    discoveredBy: "William Cruickshank",
    discoveryYear: "1807",
    source: "From Arabic 'soda' (headache remedy)",
    meltingPointC: 97.8,
    boilingPointC: 883,
    density: 0.971,
    electronegativity: 0.93,
    ionizationEnergy: 495.8,
  },
  {
    name: "Magnesium",
    symbol: "Mg",
    atomicNumber: 12,
    atomicMass: "24.31",
    category: "Alkaline Earth Metal",
    group: 2,
    period: 3,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ne] 3s²",
    summary: "Essential mineral for biological systems, used in alloys and fireworks.",
    discoveredBy: "Joseph Black",
    discoveryYear: "1755",
    source: "From Magnesia, a region in Greece",
    meltingPointC: 650,
    boilingPointC: 1091,
    density: 1.738,
    electronegativity: 1.31,
    ionizationEnergy: 738.1,
  },
  {
    name: "Aluminum",
    symbol: "Al",
    atomicNumber: 13,
    atomicMass: "26.98",
    category: "Post-transition Metal",
    group: 13,
    period: 3,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ne] 3s² 3p¹",
    summary: "Lightweight metal, third most abundant element, widely used in construction and packaging.",
    discoveredBy: "Hans Christian Ørsted",
    discoveryYear: "1825",
    source: "From Latin 'alumen' (alum)",
    meltingPointC: 660.3,
    boilingPointC: 2519,
    density: 2.7,
    electronegativity: 1.61,
    ionizationEnergy: 577.5,
  },
  {
    name: "Silicon",
    symbol: "Si",
    atomicNumber: 14,
    atomicMass: "28.09",
    category: "Metalloid",
    group: 14,
    period: 3,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ne] 3s² 3p²",
    summary: "Second most abundant element, used in semiconductors and glass.",
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: "1824",
    source: "From Latin 'silex' (flint)",
    meltingPointC: 1414,
    boilingPointC: 3265,
    density: 2.33,
    electronegativity: 1.9,
    ionizationEnergy: 786.5,
  },
  {
    name: "Phosphorus",
    symbol: "P",
    atomicNumber: 15,
    atomicMass: "30.97",
    category: "Reactive Nonmetal",
    group: 15,
    period: 3,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ne] 3s² 3p³",
    summary: "Essential for life, used in fertilizers and matches.",
    discoveredBy: "Hennig Brand",
    discoveryYear: "1669",
    source: "From Greek 'phosphoros' (light-bearing)",
    meltingPointC: 44.2,
    boilingPointC: 280.0,
    density: 1.82,
    electronegativity: 2.19,
    ionizationEnergy: 1012.0,
  },
  {
    name: "Sulfur",
    symbol: "S",
    atomicNumber: 16,
    atomicMass: "32.06",
    category: "Reactive Nonmetal",
    group: 16,
    period: 3,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ne] 3s² 3p⁴",
    summary: "Essential for proteins, has characteristic rotten egg smell in compounds.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'sulphur'",
    meltingPointC: 115.2,
    boilingPointC: 444.6,
    density: 2.07,
    electronegativity: 2.58,
    ionizationEnergy: 999.6,
  },
  {
    name: "Chlorine",
    symbol: "Cl",
    atomicNumber: 17,
    atomicMass: "35.45",
    category: "Reactive Nonmetal",
    group: 17,
    period: 3,
    phaseAtSTP: "Gas",
    electronConfiguration: "[Ne] 3s² 3p⁵",
    summary: "Toxic gas used in water purification and bleach production.",
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: "1774",
    source: "From Greek 'chloros' (greenish-yellow)",
    meltingPointC: -101.5,
    boilingPointC: -34.04,
    density: 3.214,
    electronegativity: 3.16,
    ionizationEnergy: 1251.2,
  },
  {
    name: "Argon",
    symbol: "Ar",
    atomicNumber: 18,
    atomicMass: "39.95",
    category: "Noble Gas",
    group: 18,
    period: 3,
    phaseAtSTP: "Gas",
    electronConfiguration: "[Ne] 3s² 3p⁶",
    summary: "Inert noble gas, third most abundant in atmosphere, used in welding.",
    discoveredBy: "William Ramsay",
    discoveryYear: "1894",
    source: "From Greek 'argos' (inactive)",
    meltingPointC: -189.3,
    boilingPointC: -185.8,
    density: 1.784,
    electronegativity: null,
    ionizationEnergy: 1520.6,
  },
  {
    name: "Potassium",
    symbol: "K",
    atomicNumber: 19,
    atomicMass: "39.10",
    category: "Alkali Metal",
    group: 1,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 4s¹",
    summary: "Highly reactive metal, essential electrolyte in biological systems.",
    discoveredBy: "William Cruickshank",
    discoveryYear: "1807",
    source: "From English 'potash' (pot ashes)",
    meltingPointC: 63.3,
    boilingPointC: 759,
    density: 0.862,
    electronegativity: 0.82,
    ionizationEnergy: 418.8,
  },
  {
    name: "Calcium",
    symbol: "Ca",
    atomicNumber: 20,
    atomicMass: "40.08",
    category: "Alkaline Earth Metal",
    group: 2,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 4s²",
    summary: "Essential for bones and teeth, used in construction materials.",
    discoveredBy: "William Cruickshank",
    discoveryYear: "1808",
    source: "From Latin 'calx' (lime)",
    meltingPointC: 842,
    boilingPointC: 1484,
    density: 1.55,
    electronegativity: 1.0,
    ionizationEnergy: 589.8,
  },
  {
    name: "Scandium",
    symbol: "Sc",
    atomicNumber: 21,
    atomicMass: "44.96",
    category: "Transition Metal",
    group: 3,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d¹ 4s²",
    summary: "Rare transition metal, used in high-strength alloys and sports equipment.",
    discoveredBy: "Lars Fredrik Nilson",
    discoveryYear: "1879",
    source: "From Latin 'scandens' (to climb)",
    meltingPointC: 1541,
    boilingPointC: 2836,
    density: 2.989,
    electronegativity: 1.36,
    ionizationEnergy: 631.0,
  },
  {
    name: "Titanium",
    symbol: "Ti",
    atomicNumber: 22,
    atomicMass: "47.87",
    category: "Transition Metal",
    group: 4,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d² 4s²",
    summary: "Strong, lightweight metal used in aircraft, medical implants, and pigments.",
    discoveredBy: "William Gregor",
    discoveryYear: "1791",
    source: "From Latin 'titan' (Titan)",
    meltingPointC: 1668,
    boilingPointC: 3287,
    density: 4.506,
    electronegativity: 1.54,
    ionizationEnergy: 658.8,
  },
  {
    name: "Vanadium",
    symbol: "V",
    atomicNumber: 23,
    atomicMass: "50.94",
    category: "Transition Metal",
    group: 5,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d³ 4s²",
    summary: "Hard, corrosion-resistant metal used in steel alloys and catalysts.",
    discoveredBy: "Andrés Manuel del Río",
    discoveryYear: "1801",
    source: "From Latin 'vanadium'",
    meltingPointC: 1910,
    boilingPointC: 3407,
    density: 6.11,
    electronegativity: 1.63,
    ionizationEnergy: 650.2,
  },
  {
    name: "Chromium",
    symbol: "Cr",
    atomicNumber: 24,
    atomicMass: "52.00",
    category: "Transition Metal",
    group: 6,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d⁵ 4s¹",
    summary: "Hard, lustrous metal used in stainless steel and plating.",
    discoveredBy: "Louis-Nicolas Vauquelin",
    discoveryYear: "1797",
    source: "From Latin 'chroma' (color)",
    meltingPointC: 1907,
    boilingPointC: 2671,
    density: 7.19,
    electronegativity: 1.66,
    ionizationEnergy: 652.9,
  },
  {
    name: "Manganese",
    symbol: "Mn",
    atomicNumber: 25,
    atomicMass: "54.94",
    category: "Transition Metal",
    group: 7,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d⁵ 4s²",
    summary: "Hard, brittle metal used in steel production and batteries.",
    discoveredBy: "Johan Gottlieb Gahn",
    discoveryYear: "1774",
    source: "From Latin 'mangan' (manganese)",
    meltingPointC: 1246,
    boilingPointC: 2061,
    density: 7.44,
    electronegativity: 1.55,
    ionizationEnergy: 717.3,
  },
  {
    name: "Iron",
    symbol: "Fe",
    atomicNumber: 26,
    atomicMass: "55.85",
    category: "Transition Metal",
    group: 8,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    summary: "Most abundant metal on Earth, used in construction and steel production.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'ferrum' (iron)",
    meltingPointC: 1538,
    boilingPointC: 2862,
    density: 7.87,
    electronegativity: 1.83,
    ionizationEnergy: 762.5,
  },
  {
    name: "Cobalt",
    symbol: "Co",
    atomicNumber: 27,
    atomicMass: "58.93",
    category: "Transition Metal",
    group: 9,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d⁷ 4s²",
    summary: "Hard, ferromagnetic metal used in magnets and pigments.",
    discoveredBy: "Georg Brandt",
    discoveryYear: "1735",
    source: "From Latin 'cobalt'",
    meltingPointC: 1495,
    boilingPointC: 2927,
    density: 8.86,
    electronegativity: 1.88,
    ionizationEnergy: 760.4,
  },
  {
    name: "Nickel",
    symbol: "Ni",
    atomicNumber: 28,
    atomicMass: "58.69",
    category: "Transition Metal",
    group: 10,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d⁸ 4s²",
    summary: "Hard, corrosion-resistant metal used in stainless steel and coins.",
    discoveredBy: "Axel Fredrik Cronstedt",
    discoveryYear: "1751",
    source: "From Latin 'nicco' (nickel)",
    meltingPointC: 1455,
    boilingPointC: 2913,
    density: 8.908,
    electronegativity: 1.91,
    ionizationEnergy: 737.3,
  },
  {
    name: "Copper",
    symbol: "Cu",
    atomicNumber: 29,
    atomicMass: "63.55",
    category: "Transition Metal",
    group: 11,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    summary: "Excellent conductor of electricity, used in wiring and plumbing.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'cuprum' (copper)",
    meltingPointC: 1084.6,
    boilingPointC: 2562,
    density: 8.96,
    electronegativity: 1.9,
    ionizationEnergy: 745.5,
  },
  {
    name: "Zinc",
    symbol: "Zn",
    atomicNumber: 30,
    atomicMass: "65.38",
    category: "Transition Metal",
    group: 12,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    summary: "Essential trace element used in galvanizing and brass.",
    discoveredBy: "Andreas Sigismund Marggraf",
    discoveryYear: "1746",
    source: "From Latin 'zincum' (zinc)",
    meltingPointC: 419.5,
    boilingPointC: 907,
    density: 7.14,
    electronegativity: 1.65,
    ionizationEnergy: 906.0,
  },
  {
    name: "Gallium",
    symbol: "Ga",
    atomicNumber: 31,
    atomicMass: "69.72",
    category: "Post-transition Metal",
    group: 13,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    summary: "Soft metal with low melting point, used in semiconductors and solar cells.",
    discoveredBy: "Paul-Émile Lecoq de Boisbaudran",
    discoveryYear: "1875",
    source: "From Latin 'gallia' (France)",
    meltingPointC: 29.76,
    boilingPointC: 2204,
    density: 5.904,
    electronegativity: 1.81,
    ionizationEnergy: 578.8,
  },
  {
    name: "Germanium",
    symbol: "Ge",
    atomicNumber: 32,
    atomicMass: "72.63",
    category: "Metalloid",
    group: 14,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    summary: "Semiconductor material used in fiber optics and solar cells.",
    discoveredBy: "Clemens Winkler",
    discoveryYear: "1886",
    source: "From Latin 'germanium'",
    meltingPointC: 938.25,
    boilingPointC: 2833,
    density: 5.323,
    electronegativity: 2.01,
    ionizationEnergy: 762.0,
  },
  {
    name: "Arsenic",
    symbol: "As",
    atomicNumber: 33,
    atomicMass: "74.92",
    category: "Metalloid",
    group: 15,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    summary: "Toxic metalloid used in semiconductors and pesticides.",
    discoveredBy: "Albertus Magnus",
    discoveryYear: "1250",
    source: "From Latin 'arsenicum'",
    meltingPointC: 817,
    boilingPointC: 614,
    density: 5.727,
    electronegativity: 2.18,
    ionizationEnergy: 849.6,
  },
  {
    name: "Selenium",
    symbol: "Se",
    atomicNumber: 34,
    atomicMass: "78.96",
    category: "Reactive Nonmetal",
    group: 16,
    period: 4,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    summary: "Essential trace element used in photocopiers and solar cells.",
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: "1817",
    source: "From Latin 'selenium'",
    meltingPointC: 221,
    boilingPointC: 685,
    density: 4.809,
    electronegativity: 2.55,
    ionizationEnergy: 833.8,
  },
  {
    name: "Bromine",
    symbol: "Br",
    atomicNumber: 35,
    atomicMass: "79.90",
    category: "Reactive Nonmetal",
    group: 17,
    period: 4,
    phaseAtSTP: "Liquid",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    summary: "Only liquid nonmetal at room temperature, used in flame retardants and disinfectants.",
    discoveredBy: "Antoine Jérôme Balard",
    discoveryYear: "1826",
    source: "From Greek 'bromos' (bitter)",
    meltingPointC: -7.2,
    boilingPointC: 58.8,
    density: 3.1028,
    electronegativity: 2.96,
    ionizationEnergy: 1139.9,
  },
  {
    name: "Krypton",
    symbol: "Kr",
    atomicNumber: 36,
    atomicMass: "83.80",
    category: "Noble Gas",
    group: 18,
    period: 4,
    phaseAtSTP: "Gas",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    summary: "Inert noble gas used in lighting and lasers.",
    discoveredBy: "William Ramsay",
    discoveryYear: "1898",
    source: "From Greek 'kryptos' (hidden)",
    meltingPointC: -157.38,
    boilingPointC: -153.22,
    density: 3.749,
    electronegativity: null,
    ionizationEnergy: 1350.8,
  },
  {
    name: "Rubidium",
    symbol: "Rb",
    atomicNumber: 37,
    atomicMass: "85.47",
    category: "Alkali Metal",
    group: 1,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 5s¹",
    summary: "Highly reactive alkali metal, used in atomic clocks and research.",
    discoveredBy: "Robert Bunsen",
    discoveryYear: "1861",
    source: "From Latin 'rubidus' (deep red)",
    meltingPointC: 39.3,
    boilingPointC: 688,
    density: 1.532,
    electronegativity: 0.82,
    ionizationEnergy: 403.0,
  },
  {
    name: "Strontium",
    symbol: "Sr",
    atomicNumber: 38,
    atomicMass: "87.62",
    category: "Alkaline Earth Metal",
    group: 2,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 5s²",
    summary: "Alkaline earth metal used in fireworks and ceramics.",
    discoveredBy: "Adair Crawford",
    discoveryYear: "1790",
    source: "From Latin 'strontium'",
    meltingPointC: 777,
    boilingPointC: 1382,
    density: 2.64,
    electronegativity: 0.95,
    ionizationEnergy: 549.5,
  },
  {
    name: "Yttrium",
    symbol: "Y",
    atomicNumber: 39,
    atomicMass: "88.91",
    category: "Transition Metal",
    group: 3,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹ 5s²",
    summary: "Rare earth transition metal used in superconductors and ceramics.",
    discoveredBy: "Johan Gadolin",
    discoveryYear: "1794",
    source: "From Latin 'yttrium'",
    meltingPointC: 1526,
    boilingPointC: 3345,
    density: 4.469,
    electronegativity: 1.22,
    ionizationEnergy: 615.0,
  },
  {
    name: "Zirconium",
    symbol: "Zr",
    atomicNumber: 40,
    atomicMass: "91.22",
    category: "Transition Metal",
    group: 4,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d² 5s²",
    summary: "Corrosion-resistant metal used in nuclear reactors and ceramics.",
    discoveredBy: "Martin Heinrich Klaproth",
    discoveryYear: "1789",
    source: "From Latin 'zircon'",
    meltingPointC: 1855,
    boilingPointC: 4409,
    density: 6.506,
    electronegativity: 1.33,
    ionizationEnergy: 660.3,
  },
  {
    name: "Niobium",
    symbol: "Nb",
    atomicNumber: 41,
    atomicMass: "92.91",
    category: "Transition Metal",
    group: 5,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d⁴ 5s¹",
    summary: "Hard, refractory metal used in superconductors and high-strength alloys.",
    discoveredBy: "Charles Hatchett",
    discoveryYear: "1801",
    source: "From Latin 'niobium'",
    meltingPointC: 2477,
    boilingPointC: 4744,
    density: 8.57,
    electronegativity: 1.6,
    ionizationEnergy: 630.0,
  },
  {
    name: "Molybdenum",
    symbol: "Mo",
    atomicNumber: 42,
    atomicMass: "95.95",
    category: "Transition Metal",
    group: 6,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d⁵ 5s¹",
    summary: "Hard, refractory metal used in steel alloys and catalysts.",
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: "1778",
    source: "From Latin 'molybdaem'",
    meltingPointC: 2623,
    boilingPointC: 4639,
    density: 10.28,
    electronegativity: 2.16,
    ionizationEnergy: 660.4,
  },
  {
    name: "Technetium",
    symbol: "Tc",
    atomicNumber: 43,
    atomicMass: "98.00",
    category: "Transition Metal",
    group: 7,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d⁵ 5s²",
    summary: "First synthetic element, used in medical imaging and research.",
    discoveredBy: "Emilio Segrè",
    discoveryYear: "1937",
    source: "From Greek 'technetos' (artificial)",
    meltingPointC: 2157,
    boilingPointC: 4265,
    density: 11.5,
    electronegativity: 1.9,
    ionizationEnergy: 670.0,
  },
  {
    name: "Ruthenium",
    symbol: "Ru",
    atomicNumber: 44,
    atomicMass: "101.07",
    category: "Transition Metal",
    group: 8,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d⁷ 5s¹",
    summary: "Hard, silvery metal used in catalysts and electronics.",
    discoveredBy: "Karl Ernst Claus",
    discoveryYear: "1844",
    source: "From Latin 'ruthenium'",
    meltingPointC: 2334,
    boilingPointC: 4150,
    density: 12.37,
    electronegativity: 2.2,
    ionizationEnergy: 690.0,
  },
  {
    name: "Rhodium",
    symbol: "Rh",
    atomicNumber: 45,
    atomicMass: "102.91",
    category: "Transition Metal",
    group: 9,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d⁸ 5s¹",
    summary: "Rare, precious metal used in catalytic converters and jewelry.",
    discoveredBy: "William Hyde Wollaston",
    discoveryYear: "1803",
    source: "From Greek 'rhodon' (rose)",
    meltingPointC: 1964,
    boilingPointC: 3695,
    density: 12.41,
    electronegativity: 2.28,
    ionizationEnergy: 700.0,
  },
  {
    name: "Palladium",
    symbol: "Pd",
    atomicNumber: 46,
    atomicMass: "106.42",
    category: "Transition Metal",
    group: 10,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰",
    summary: "Precious metal, excellent catalyst used in catalytic converters.",
    discoveredBy: "William Hyde Wollaston",
    discoveryYear: "1803",
    source: "From Latin 'palladium'",
    meltingPointC: 1555,
    boilingPointC: 2963,
    density: 12.02,
    electronegativity: 2.2,
    ionizationEnergy: 717.0,
  },
  {
    name: "Silver",
    symbol: "Ag",
    atomicNumber: 47,
    atomicMass: "107.87",
    category: "Transition Metal",
    group: 11,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
    summary: "Precious metal with excellent conductivity, used in jewelry and electronics.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'argentum' (silver)",
    meltingPointC: 961.8,
    boilingPointC: 2162,
    density: 10.49,
    electronegativity: 1.93,
    ionizationEnergy: 730.0,
  },
  {
    name: "Cadmium",
    symbol: "Cd",
    atomicNumber: 48,
    atomicMass: "112.41",
    category: "Transition Metal",
    group: 12,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰ 5s²",
    summary: "Toxic metal used in batteries and pigments.",
    discoveredBy: "Friedrich Stromeyer",
    discoveryYear: "1817",
    source: "From Latin 'cadmia'",
    meltingPointC: 321.07,
    boilingPointC: 767,
    density: 8.65,
    electronegativity: 1.69,
    ionizationEnergy: 760.0,
  },
  {
    name: "Indium",
    symbol: "In",
    atomicNumber: 49,
    atomicMass: "114.82",
    category: "Post-transition Metal",
    group: 13,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
    summary: "Soft, malleable metal used in semiconductors and solar cells.",
    discoveredBy: "Ferdinand Reich",
    discoveryYear: "1863",
    source: "From Latin 'indium'",
    meltingPointC: 156.6,
    boilingPointC: 2072,
    density: 7.31,
    electronegativity: 1.78,
    ionizationEnergy: 578.8,
  },
  {
    name: "Tin",
    symbol: "Sn",
    atomicNumber: 50,
    atomicMass: "118.71",
    category: "Post-transition Metal",
    group: 14,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
    summary: "Malleable metal used in bronze and solder.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'stannum'",
    meltingPointC: 231.93,
    boilingPointC: 2602,
    density: 7.287,
    electronegativity: 1.96,
    ionizationEnergy: 708.0,
  },
  {
    name: "Antimony",
    symbol: "Sb",
    atomicNumber: 51,
    atomicMass: "121.76",
    category: "Metalloid",
    group: 15,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
    summary: "Brittle metalloid used in alloys and flame retardants.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'stibium'",
    meltingPointC: 630.63,
    boilingPointC: 1587,
    density: 6.685,
    electronegativity: 2.05,
    ionizationEnergy: 834.0,
  },
  {
    name: "Tellurium",
    symbol: "Te",
    atomicNumber: 52,
    atomicMass: "127.60",
    category: "Metalloid",
    group: 16,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    summary: "Brittle metalloid used in solar cells and thermoelectric devices.",
    discoveredBy: "Franz-Joseph Müller",
    discoveryYear: "1782",
    source: "From Latin 'tellus' (earth)",
    meltingPointC: 449.51,
    boilingPointC: 988,
    density: 6.232,
    electronegativity: 2.1,
    ionizationEnergy: 834.0,
  },
  {
    name: "Iodine",
    symbol: "I",
    atomicNumber: 53,
    atomicMass: "126.90",
    category: "Reactive Nonmetal",
    group: 17,
    period: 5,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    summary: "Essential for thyroid function, used in disinfectants and photography.",
    discoveredBy: "Bernard Courtois",
    discoveryYear: "1811",
    source: "From Greek 'eidos' (form)",
    meltingPointC: 113.7,
    boilingPointC: 184.4,
    density: 4.933,
    electronegativity: 2.66,
    ionizationEnergy: 1008.0,
  },
  {
    name: "Xenon",
    symbol: "Xe",
    atomicNumber: 54,
    atomicMass: "131.29",
    category: "Noble Gas",
    group: 18,
    period: 5,
    phaseAtSTP: "Gas",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    summary: "Inert noble gas used in lighting and anesthesia.",
    discoveredBy: "William Ramsay",
    discoveryYear: "1898",
    source: "From Greek 'xenos' (stranger)",
    meltingPointC: -111.75,
    boilingPointC: -108.12,
    density: 5.894,
    electronegativity: null,
    ionizationEnergy: 1170.0,
  },
  {
    name: "Cesium",
    symbol: "Cs",
    atomicNumber: 55,
    atomicMass: "132.91",
    category: "Alkali Metal",
    group: 1,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 6s¹",
    summary: "Highly reactive alkali metal, used in atomic clocks and research.",
    discoveredBy: "Robert Bunsen",
    discoveryYear: "1860",
    source: "From Latin 'caesius' (sky blue)",
    meltingPointC: 28.44,
    boilingPointC: 671,
    density: 1.873,
    electronegativity: 0.79,
    ionizationEnergy: 375.7,
  },
  {
    name: "Barium",
    symbol: "Ba",
    atomicNumber: 56,
    atomicMass: "137.33",
    category: "Alkaline Earth Metal",
    group: 2,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 6s²",
    summary: "Alkaline earth metal used in medical imaging and ceramics.",
    discoveredBy: "Humphry Davy",
    discoveryYear: "1808",
    source: "From Latin 'barium'",
    meltingPointC: 727,
    boilingPointC: 1845,
    density: 3.594,
    electronegativity: 0.89,
    ionizationEnergy: 502.9,
  },
  {
    name: "Lanthanum",
    symbol: "La",
    atomicNumber: 57,
    atomicMass: "138.91",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 5d¹ 6s²",
    summary: "Rare earth element used in catalysts and optics.",
    discoveredBy: "Carl Gustaf Mosander",
    discoveryYear: "1839",
    source: "From Latin 'lanthanum'",
    meltingPointC: 920,
    boilingPointC: 3464,
    density: 6.145,
    electronegativity: 1.1,
    ionizationEnergy: 508.0,
  },
  {
    name: "Cerium",
    symbol: "Ce",
    atomicNumber: 58,
    atomicMass: "140.12",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
    summary: "Most abundant rare earth element, used in catalytic converters and polishing.",
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: "1803",
    source: "From Latin 'cerium'",
    meltingPointC: 798,
    boilingPointC: 3257,
    density: 6.77,
    electronegativity: 1.12,
    ionizationEnergy: 508.0,
  },
  {
    name: "Praseodymium",
    symbol: "Pr",
    atomicNumber: 59,
    atomicMass: "140.91",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f³ 6s²",
    summary: "Rare earth element used in magnets and alloys.",
    discoveredBy: "Carl Auer von Welsbach",
    discoveryYear: "1885",
    source: "From Greek 'pras' (first)",
    meltingPointC: 931,
    boilingPointC: 3520,
    density: 6.773,
    electronegativity: 1.13,
    ionizationEnergy: 508.0,
  },
  {
    name: "Neodymium",
    symbol: "Nd",
    atomicNumber: 60,
    atomicMass: "144.24",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f⁴ 6s²",
    summary: "Rare earth element used in powerful magnets and lasers.",
    discoveredBy: "Carl Auer von Welsbach",
    discoveryYear: "1885",
    source: "From Greek 'neos' (new)",
    meltingPointC: 1016,
    boilingPointC: 3074,
    density: 7.007,
    electronegativity: 1.14,
    ionizationEnergy: 508.0,
  },
  {
    name: "Promethium",
    symbol: "Pm",
    atomicNumber: 61,
    atomicMass: "145.00",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f⁵ 6s²",
    summary: "Radioactive rare earth element used in atomic batteries and luminous paint.",
    discoveredBy: "Jacob A. Marinsky",
    discoveryYear: "1945",
    source: "From Greek 'prometheus'",
    meltingPointC: 1080,
    boilingPointC: 2730,
    density: 7.26,
    electronegativity: 1.13,
    ionizationEnergy: 508.0,
  },
  {
    name: "Samarium",
    symbol: "Sm",
    atomicNumber: 62,
    atomicMass: "150.36",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f⁶ 6s²",
    summary: "Rare earth element used in magnets and medical applications.",
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveryYear: "1879",
    source: "From Latin 'samarium'",
    meltingPointC: 1072,
    boilingPointC: 1900,
    density: 7.52,
    electronegativity: 1.17,
    ionizationEnergy: 508.0,
  },
  {
    name: "Europium",
    symbol: "Eu",
    atomicNumber: 63,
    atomicMass: "151.96",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f⁷ 6s²",
    summary: "Rare earth element used in phosphors and nuclear applications.",
    discoveredBy: "Eugène-Anatole Demarçay",
    discoveryYear: "1901",
    source: "From Greek 'eu' (good)",
    meltingPointC: 822,
    boilingPointC: 1597,
    density: 5.243,
    electronegativity: 1.2,
    ionizationEnergy: 508.0,
  },
  {
    name: "Gadolinium",
    symbol: "Gd",
    atomicNumber: 64,
    atomicMass: "157.25",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
    summary: "Rare earth element used in MRI contrast agents and magnets.",
    discoveredBy: "Jean Charles Galissard de Marignac",
    discoveryYear: "1880",
    source: "From Latin 'gadolinium'",
    meltingPointC: 1313,
    boilingPointC: 3273,
    density: 7.895,
    electronegativity: 1.2,
    ionizationEnergy: 508.0,
  },
  {
    name: "Terbium",
    symbol: "Tb",
    atomicNumber: 65,
    atomicMass: "158.93",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f⁹ 6s²",
    summary: "Rare earth element used in magnets and phosphors.",
    discoveredBy: "Carl Gustaf Mosander",
    discoveryYear: "1843",
    source: "From Latin 'terebium'",
    meltingPointC: 1356,
    boilingPointC: 3230,
    density: 8.229,
    electronegativity: 1.1,
    ionizationEnergy: 508.0,
  },
  {
    name: "Dysprosium",
    symbol: "Dy",
    atomicNumber: 66,
    atomicMass: "162.50",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁰ 6s²",
    summary: "Rare earth element used in high-performance magnets and lasers.",
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveryYear: "1886",
    source: "From Latin 'dysprosium'",
    meltingPointC: 1412,
    boilingPointC: 2567,
    density: 8.55,
    electronegativity: 1.22,
    ionizationEnergy: 508.0,
  },
  {
    name: "Holmium",
    symbol: "Ho",
    atomicNumber: 67,
    atomicMass: "164.93",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹¹ 6s²",
    summary: "Rare earth element used in lasers and high-performance magnets.",
    discoveredBy: "Per Teodor Cleve",
    discoveryYear: "1878",
    source: "From Latin 'holmium'",
    meltingPointC: 1474,
    boilingPointC: 2700,
    density: 8.795,
    electronegativity: 1.23,
    ionizationEnergy: 508.0,
  },
  {
    name: "Erbium",
    symbol: "Er",
    atomicNumber: 68,
    atomicMass: "167.26",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹² 6s²",
    summary: "Rare earth element used in fiber optics and lasers.",
    discoveredBy: "Carl Gustaf Mosander",
    discoveryYear: "1843",
    source: "From Latin 'erbium'",
    meltingPointC: 1529,
    boilingPointC: 2868,
    density: 9.066,
    electronegativity: 1.24,
    ionizationEnergy: 508.0,
  },
  {
    name: "Thulium",
    symbol: "Tm",
    atomicNumber: 69,
    atomicMass: "168.93",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹³ 6s²",
    summary: "Rare earth element used in portable X-ray devices and lasers.",
    discoveredBy: "Per Teodor Cleve",
    discoveryYear: "1879",
    source: "From Latin 'thulium'",
    meltingPointC: 1545,
    boilingPointC: 1950,
    density: 9.321,
    electronegativity: 1.25,
    ionizationEnergy: 508.0,
  },
  {
    name: "Ytterbium",
    symbol: "Yb",
    atomicNumber: 70,
    atomicMass: "173.04",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 6s²",
    summary: "Rare earth element used in alloys and lasers.",
    discoveredBy: "Jean Charles Galissard de Marignac",
    discoveryYear: "1878",
    source: "From Latin 'ytterium'",
    meltingPointC: 819,
    boilingPointC: 1196,
    density: 6.965,
    electronegativity: 1.1,
    ionizationEnergy: 508.0,
  },
  {
    name: "Lutetium",
    symbol: "Lu",
    atomicNumber: 71,
    atomicMass: "174.97",
    category: "Lanthanide",
    group: 3,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    summary: "Rare earth element used in catalysts and medical applications.",
    discoveredBy: "Georges Urbain",
    discoveryYear: "1907",
    source: "From Latin 'lutetium'",
    meltingPointC: 1663,
    boilingPointC: 3402,
    density: 9.84,
    electronegativity: 1.27,
    ionizationEnergy: 508.0,
  },
  {
    name: "Hafnium",
    symbol: "Hf",
    atomicNumber: 72,
    atomicMass: "178.49",
    category: "Transition Metal",
    group: 4,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
    summary: "Hard, refractory metal used in nuclear reactors and high-strength alloys.",
    discoveredBy: "Dirk Coster",
    discoveryYear: "1923",
    source: "From Latin 'hafnia' (capital of Denmark)",
    meltingPointC: 2233,
    boilingPointC: 4603,
    density: 13.31,
    electronegativity: 1.3,
    ionizationEnergy: 647.0,
  },
  {
    name: "Tantalum",
    symbol: "Ta",
    atomicNumber: 73,
    atomicMass: "180.95",
    category: "Transition Metal",
    group: 5,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
    summary: "Hard, corrosion-resistant metal used in electronics and medical implants.",
    discoveredBy: "Anders Gustaf Ekeberg",
    discoveryYear: "1802",
    source: "From Latin 'tantalum'",
    meltingPointC: 3290,
    boilingPointC: 5731,
    density: 16.69,
    electronegativity: 1.5,
    ionizationEnergy: 649.0,
  },
  {
    name: "Tungsten",
    symbol: "W",
    atomicNumber: 74,
    atomicMass: "183.84",
    category: "Transition Metal",
    group: 6,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    summary: "Highest melting point of all metals, used in light bulbs and cutting tools.",
    discoveredBy: "Juan José Elhuyar",
    discoveryYear: "1783",
    source: "From Latin 'wolfram'",
    meltingPointC: 3422,
    boilingPointC: 5555,
    density: 19.25,
    electronegativity: 2.36,
    ionizationEnergy: 651.0,
  },
  {
    name: "Rhenium",
    symbol: "Re",
    atomicNumber: 75,
    atomicMass: "186.21",
    category: "Transition Metal",
    group: 7,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    summary: "Hard, refractory metal used in high-performance alloys and catalysts.",
    discoveredBy: "Ida Tacke",
    discoveryYear: "1925",
    source: "From Latin 'rhenum'",
    meltingPointC: 3186,
    boilingPointC: 5596,
    density: 21.02,
    electronegativity: 1.9,
    ionizationEnergy: 651.0,
  },
  {
    name: "Osmium",
    symbol: "Os",
    atomicNumber: 76,
    atomicMass: "190.23",
    category: "Transition Metal",
    group: 8,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    summary: "Densest naturally occurring element, used in alloys and filaments.",
    discoveredBy: "Smithson Tennant",
    discoveryYear: "1803",
    source: "From Latin 'osmium'",
    meltingPointC: 3033,
    boilingPointC: 5012,
    density: 22.59,
    electronegativity: 2.2,
    ionizationEnergy: 651.0,
  },
  {
    name: "Iridium",
    symbol: "Ir",
    atomicNumber: 77,
    atomicMass: "192.22",
    category: "Transition Metal",
    group: 9,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    summary: "Hard, corrosion-resistant metal used in high-performance alloys and catalysts.",
    discoveredBy: "Smithson Tennant",
    discoveryYear: "1803",
    source: "From Latin 'iridium'",
    meltingPointC: 2446,
    boilingPointC: 4428,
    density: 22.56,
    electronegativity: 2.2,
    ionizationEnergy: 651.0,
  },
  {
    name: "Platinum",
    symbol: "Pt",
    atomicNumber: 78,
    atomicMass: "195.08",
    category: "Transition Metal",
    group: 10,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    summary: "Precious metal, excellent catalyst used in catalytic converters and electronics.",
    discoveredBy: "Antonio de Ulloa",
    discoveryYear: "1735",
    source: "From Latin 'platinum'",
    meltingPointC: 1768.4,
    boilingPointC: 3825,
    density: 21.45,
    electronegativity: 2.28,
    ionizationEnergy: 651.0,
  },
  {
    name: "Gold",
    symbol: "Au",
    atomicNumber: 79,
    atomicMass: "196.97",
    category: "Transition Metal",
    group: 11,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    summary: "Precious metal, highly valued for jewelry and electronics.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'aurum'",
    meltingPointC: 1064.18,
    boilingPointC: 2856,
    density: 19.3,
    electronegativity: 2.54,
    ionizationEnergy: 651.0,
  },
  {
    name: "Mercury",
    symbol: "Hg",
    atomicNumber: 80,
    atomicMass: "200.59",
    category: "Transition Metal",
    group: 12,
    period: 6,
    phaseAtSTP: "Liquid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    summary: "Only liquid metal at room temperature, used in thermometers and dental amalgam.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'hydrargyrum' (liquid silver)",
    meltingPointC: -38.83,
    boilingPointC: 356.73,
    density: 13.5336,
    electronegativity: 2.23,
    ionizationEnergy: 651.0,
  },
  {
    name: "Thallium",
    symbol: "Tl",
    atomicNumber: 81,
    atomicMass: "204.38",
    category: "Post-transition Metal",
    group: 13,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    summary: "Toxic metal used in semiconductors and photocells.",
    discoveredBy: "William Crookes",
    discoveryYear: "1861",
    source: "From Latin 'thallium'",
    meltingPointC: 304,
    boilingPointC: 1457,
    density: 11.85,
    electronegativity: 1.62,
    ionizationEnergy: 651.0,
  },
  {
    name: "Lead",
    symbol: "Pb",
    atomicNumber: 82,
    atomicMass: "207.2",
    category: "Post-transition Metal",
    group: 14,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    summary: "Dense metal used in batteries and radiation shielding.",
    discoveredBy: "Ancient civilizations",
    discoveryYear: "Ancient",
    source: "From Latin 'plumbum'",
    meltingPointC: 327.46,
    boilingPointC: 1749,
    density: 11.34,
    electronegativity: 2.33,
    ionizationEnergy: 651.0,
  },
  {
    name: "Bismuth",
    symbol: "Bi",
    atomicNumber: 83,
    atomicMass: "208.98",
    category: "Post-transition Metal",
    group: 15,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    summary: "Brittle metal used in alloys and cosmetics.",
    discoveredBy: "Claude François Geoffroy",
    discoveryYear: "1753",
    source: "From Latin 'bismuth'",
    meltingPointC: 271.5,
    boilingPointC: 1564,
    density: 9.807,
    electronegativity: 2.02,
    ionizationEnergy: 651.0,
  },
  {
    name: "Polonium",
    symbol: "Po",
    atomicNumber: 84,
    atomicMass: "209.00",
    category: "Metalloid",
    group: 16,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    summary: "Radioactive metalloid used in research and heat sources.",
    discoveredBy: "Marie Curie",
    discoveryYear: "1898",
    source: "From Latin 'polonium'",
    meltingPointC: 254,
    boilingPointC: 962,
    density: 9.196,
    electronegativity: 2.0,
    ionizationEnergy: 651.0,
  },
  {
    name: "Astatine",
    symbol: "At",
    atomicNumber: 85,
    atomicMass: "210.00",
    category: "Reactive Nonmetal",
    group: 17,
    period: 6,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    summary: "Radioactive halogen used in research and medical imaging.",
    discoveredBy: "Emilio Segrè",
    discoveryYear: "1940",
    source: "From Greek 'astatos' (unstable)",
    meltingPointC: 302,
    boilingPointC: 337,
    density: 7.0,
    electronegativity: 2.2,
    ionizationEnergy: 651.0,
  },
  {
    name: "Radon",
    symbol: "Rn",
    atomicNumber: 86,
    atomicMass: "222.00",
    category: "Noble Gas",
    group: 18,
    period: 6,
    phaseAtSTP: "Gas",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    summary: "Radioactive noble gas used in medical research and radon testing.",
    discoveredBy: "Friedrich Ernst Dorn",
    discoveryYear: "1900",
    source: "From Latin 'radon'",
    meltingPointC: -71,
    boilingPointC: -61.85,
    density: 9.73,
    electronegativity: null,
    ionizationEnergy: 651.0,
  },
  {
    name: "Francium",
    symbol: "Fr",
    atomicNumber: 87,
    atomicMass: "223.00",
    category: "Alkali Metal",
    group: 1,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 7s¹",
    summary: "Rarest naturally occurring element, used in research and nuclear physics.",
    discoveredBy: "Marguerite Perey",
    discoveryYear: "1939",
    source: "From Latin 'francium'",
    meltingPointC: 8.0,
    boilingPointC: 1050,
    density: 1.87,
    electronegativity: 0.7,
    ionizationEnergy: 651.0,
  },
  {
    name: "Radium",
    symbol: "Ra",
    atomicNumber: 88,
    atomicMass: "226.00",
    category: "Alkaline Earth Metal",
    group: 2,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 7s²",
    summary: "Radioactive alkaline earth metal used in medical research and luminous paint.",
    discoveredBy: "Marie Curie",
    discoveryYear: "1898",
    source: "From Latin 'radius' (ray)",
    meltingPointC: 700,
    boilingPointC: 1737,
    density: 5.5,
    electronegativity: 0.9,
    ionizationEnergy: 651.0,
  },
  {
    name: "Actinium",
    symbol: "Ac",
    atomicNumber: 89,
    atomicMass: "227.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 6d¹ 7s²",
    summary: "Radioactive actinide used in research and heat sources.",
    discoveredBy: "André-Louis Debierne",
    discoveryYear: "1899",
    source: "From Latin 'actinium'",
    meltingPointC: 1050,
    boilingPointC: 3200,
    density: 10.07,
    electronegativity: 1.1,
    ionizationEnergy: 651.0,
  },
  {
    name: "Thorium",
    symbol: "Th",
    atomicNumber: 90,
    atomicMass: "232.04",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 6d² 7s²",
    summary: "Radioactive actinide used in nuclear fuel and research.",
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: "1828",
    source: "From Latin 'thorium'",
    meltingPointC: 1842,
    boilingPointC: 4788,
    density: 11.72,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Protactinium",
    symbol: "Pa",
    atomicNumber: 91,
    atomicMass: "231.04",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Kasimir Fajans",
    discoveryYear: "1913",
    source: "From Latin 'protactinium'",
    meltingPointC: 1568,
    boilingPointC: 4027,
    density: 15.37,
    electronegativity: 1.5,
    ionizationEnergy: 651.0,
  },
  {
    name: "Uranium",
    symbol: "U",
    atomicNumber: 92,
    atomicMass: "238.03",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
    summary: "Radioactive actinide, nuclear fuel used in power plants and weapons.",
    discoveredBy: "Martin Heinrich Klaproth",
    discoveryYear: "1789",
    source: "From Latin 'uranium'",
    meltingPointC: 1135,
    boilingPointC: 4131,
    density: 19.1,
    electronegativity: 1.38,
    ionizationEnergy: 651.0,
  },
  {
    name: "Neptunium",
    symbol: "Np",
    atomicNumber: 93,
    atomicMass: "237.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Edwin McMillan",
    discoveryYear: "1940",
    source: "From Latin 'neptunium'",
    meltingPointC: 644,
    boilingPointC: 3902,
    density: 20.45,
    electronegativity: 1.36,
    ionizationEnergy: 651.0,
  },
  {
    name: "Plutonium",
    symbol: "Pu",
    atomicNumber: 94,
    atomicMass: "244.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f⁶ 7s²",
    summary: "Radioactive actinide used in nuclear weapons and power generation.",
    discoveredBy: "Glenn T. Seaborg",
    discoveryYear: "1940",
    source: "From Latin 'plutonium'",
    meltingPointC: 640,
    boilingPointC: 3228,
    density: 19.816,
    electronegativity: 1.28,
    ionizationEnergy: 651.0,
  },
  {
    name: "Americium",
    symbol: "Am",
    atomicNumber: 95,
    atomicMass: "243.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f⁷ 7s²",
    summary: "Radioactive actinide used in smoke detectors and research.",
    discoveredBy: "Glenn T. Seaborg",
    discoveryYear: "1944",
    source: "From Latin 'americium'",
    meltingPointC: 1176,
    boilingPointC: 2607,
    density: 13.67,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Curium",
    symbol: "Cm",
    atomicNumber: 96,
    atomicMass: "247.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
    summary: "Radioactive actinide used in research and heat sources.",
    discoveredBy: "Glenn T. Seaborg",
    discoveryYear: "1944",
    source: "From Latin 'curium'",
    meltingPointC: 1345,
    boilingPointC: 3110,
    density: 13.51,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Berkelium",
    symbol: "Bk",
    atomicNumber: 97,
    atomicMass: "247.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f⁹ 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Glenn T. Seaborg",
    discoveryYear: "1949",
    source: "From Latin 'berkelium'",
    meltingPointC: 1259,
    boilingPointC: 2627,
    density: 14.78,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Californium",
    symbol: "Cf",
    atomicNumber: 98,
    atomicMass: "251.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁰ 7s²",
    summary: "Radioactive actinide used in research and neutron sources.",
    discoveredBy: "Glenn T. Seaborg",
    discoveryYear: "1950",
    source: "From Latin 'californium'",
    meltingPointC: 900,
    boilingPointC: 1745,
    density: 15.1,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Einsteinium",
    symbol: "Es",
    atomicNumber: 99,
    atomicMass: "252.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹¹ 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1952",
    source: "From Latin 'einsteinium'",
    meltingPointC: 860,
    boilingPointC: 1527,
    density: 8.84,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Fermium",
    symbol: "Fm",
    atomicNumber: 100,
    atomicMass: "257.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹² 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1952",
    source: "From Latin 'fermium'",
    meltingPointC: 1527,
    boilingPointC: 1800,
    density: 9.7,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Mendelevium",
    symbol: "Md",
    atomicNumber: 101,
    atomicMass: "258.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹³ 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1955",
    source: "From Latin 'mendelevium'",
    meltingPointC: 827,
    boilingPointC: 1627,
    density: 10.3,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Nobelium",
    symbol: "No",
    atomicNumber: 102,
    atomicMass: "259.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1958",
    source: "From Latin 'nobelium'",
    meltingPointC: 827,
    boilingPointC: 1100,
    density: 9.9,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Lawrencium",
    symbol: "Lr",
    atomicNumber: 103,
    atomicMass: "262.00",
    category: "Actinide",
    group: 3,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹ 7s²",
    summary: "Radioactive actinide used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1961",
    source: "From Latin 'lawrencium'",
    meltingPointC: 1627,
    boilingPointC: 1800,
    density: 15.6,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Rutherfordium",
    symbol: "Rf",
    atomicNumber: 104,
    atomicMass: "267.00",
    category: "Transition Metal",
    group: 4,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1969",
    source: "From Latin 'rutherfordium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 23.2,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Dubnium",
    symbol: "Db",
    atomicNumber: 105,
    atomicMass: "268.00",
    category: "Transition Metal",
    group: 5,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1970",
    source: "From Latin 'dubnium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 29.3,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Seaborgium",
    symbol: "Sg",
    atomicNumber: 106,
    atomicMass: "271.00",
    category: "Transition Metal",
    group: 6,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Albert Ghiorso",
    discoveryYear: "1974",
    source: "From Latin 'seaborgium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 35.0,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Bohrium",
    symbol: "Bh",
    atomicNumber: 107,
    atomicMass: "272.00",
    category: "Transition Metal",
    group: 7,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Peter Armbruster",
    discoveryYear: "1981",
    source: "From Latin 'bohrium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 37.1,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Hassium",
    symbol: "Hs",
    atomicNumber: 108,
    atomicMass: "270.00",
    category: "Transition Metal",
    group: 8,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Peter Armbruster",
    discoveryYear: "1984",
    source: "From Latin 'hassium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 40.7,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Meitnerium",
    symbol: "Mt",
    atomicNumber: 109,
    atomicMass: "278.00",
    category: "Transition Metal",
    group: 9,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Peter Armbruster",
    discoveryYear: "1982",
    source: "From Latin 'meitnerium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 37.4,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Darmstadtium",
    symbol: "Ds",
    atomicNumber: 110,
    atomicMass: "281.00",
    category: "Transition Metal",
    group: 10,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s¹",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Peter Armbruster",
    discoveryYear: "1994",
    source: "From Latin 'darmstadtium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 34.8,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Roentgenium",
    symbol: "Rg",
    atomicNumber: 111,
    atomicMass: "280.00",
    category: "Transition Metal",
    group: 11,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Peter Armbruster",
    discoveryYear: "1994",
    source: "From Latin 'roentgenium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 28.7,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Copernicium",
    symbol: "Cn",
    atomicNumber: 112,
    atomicMass: "285.00",
    category: "Transition Metal",
    group: 12,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Peter Armbruster",
    discoveryYear: "1996",
    source: "From Latin 'copernicium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 23.7,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Nihonium",
    symbol: "Nh",
    atomicNumber: 113,
    atomicMass: "284.00",
    category: "Post-transition Metal",
    group: 13,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Kosuke Morita",
    discoveryYear: "2004",
    source: "From Latin 'nihonium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 16.0,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Flerovium",
    symbol: "Fl",
    atomicNumber: 114,
    atomicMass: "289.00",
    category: "Post-transition Metal",
    group: 14,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Yuri Oganessian",
    discoveryYear: "1999",
    source: "From Latin 'flerovium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 14.0,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Moscovium",
    symbol: "Mc",
    atomicNumber: 115,
    atomicMass: "288.00",
    category: "Post-transition Metal",
    group: 15,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Yuri Oganessian",
    discoveryYear: "2003",
    source: "From Latin 'moscovium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 13.5,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Livermorium",
    symbol: "Lv",
    atomicNumber: 116,
    atomicMass: "293.00",
    category: "Post-transition Metal",
    group: 16,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Yuri Oganessian",
    discoveryYear: "2000",
    source: "From Latin 'livermorium'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 12.9,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Tennessine",
    symbol: "Ts",
    atomicNumber: 117,
    atomicMass: "294.00",
    category: "Reactive Nonmetal",
    group: 17,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Yuri Oganessian",
    discoveryYear: "2010",
    source: "From Latin 'tennessine'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 7.2,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
  {
    name: "Oganesson",
    symbol: "Og",
    atomicNumber: 118,
    atomicMass: "294.00",
    category: "Noble Gas",
    group: 18,
    period: 7,
    phaseAtSTP: "Solid",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    summary: "Synthetic superheavy element used in research and nuclear physics.",
    discoveredBy: "Yuri Oganessian",
    discoveryYear: "2006",
    source: "From Latin 'oganesson'",
    meltingPointC: 2400,
    boilingPointC: 5800,
    density: 5.0,
    electronegativity: 1.3,
    ionizationEnergy: 651.0,
  },
]

const categoryColors: Record<string, string> = {
  "Alkali Metal": "bg-red-500 hover:bg-red-600",
  "Alkaline Earth Metal": "bg-orange-500 hover:bg-orange-600",
  "Transition Metal": "bg-yellow-500 hover:bg-yellow-600",
  "Post-transition Metal": "bg-green-500 hover:bg-green-600",
  Metalloid: "bg-teal-500 hover:bg-teal-600",
  "Reactive Nonmetal": "bg-blue-500 hover:bg-blue-600",
  "Noble Gas": "bg-purple-500 hover:bg-purple-600",
  Lanthanide: "bg-pink-500 hover:bg-pink-600",
  Actinide: "bg-indigo-500 hover:bg-indigo-600",
  Unknown: "bg-gray-500 hover:bg-gray-600",
}

interface ElementCellProps {
  element: Element
  isSelected: boolean
  onClick: () => void
}

function ElementCell({ element, isSelected, onClick }: ElementCellProps) {
  const categoryColor = categoryColors[element.category] || "bg-gray-500"

  return (
    <button
      onClick={onClick}
      className={`
        relative w-10 h-10 sm:w-12 sm:h-12 border rounded cursor-pointer
        transition-all duration-200 transform
        ${isSelected ? "ring-2 ring-offset-1 ring-primary scale-105 shadow-lg" : "hover:scale-103 shadow-sm"}
        ${categoryColor} text-white font-bold
        flex flex-col items-center justify-center text-center
        group
      `}
      title={element.name}
    >
      <div className="text-[7px] sm:text-[8px] absolute top-0.5 left-0.5 font-semibold">{element.atomicNumber}</div>
      <div className="text-xs sm:text-sm font-black">{element.symbol}</div>
      <div className="text-[6px] sm:text-[7px] absolute bottom-0.5 leading-tight opacity-90">{element.atomicMass}</div>
    </button>
  )
}

export function PeriodicTable() {
  const [selectedElement, setSelectedElement] = useState<Element | null>(null)
  const [searchTerm, setSearchTerm] = useState("")
  const [filterCategory, setFilterCategory] = useState<string>("all")

  const filteredElements = allElements.filter((element) => {
    const matchesSearch =
      element.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      element.symbol.toLowerCase().includes(searchTerm.toLowerCase()) ||
      element.atomicNumber.toString().includes(searchTerm)
    const matchesCategory = filterCategory === "all" || element.category === filterCategory

    return matchesSearch && matchesCategory
  })

  const categories = Array.from(new Set(allElements.map((e) => e.category))).sort()

  // Separate lanthanides and actinides
  const mainTableElements = filteredElements.filter((e) => e.category !== "Lanthanide" && e.category !== "Actinide")
  const lanthanides = filteredElements
    .filter((e) => e.category === "Lanthanide")
    .sort((a, b) => a.atomicNumber - b.atomicNumber)
  const actinides = filteredElements
    .filter((e) => e.category === "Actinide")
    .sort((a, b) => a.atomicNumber - b.atomicNumber)

  // Helper function to get element by group and period
  const getElementByPosition = (group: number, period: number) => {
    return mainTableElements.find((e) => e.group === group && e.period === period)
  }

  return (
    <div className="w-full space-y-3">
      {/* Search and Filter Controls */}
      <div className="flex flex-col sm:flex-row gap-2 items-center justify-between">
        <div className="relative flex-1 max-w-sm w-full">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search element..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10 text-sm py-1 h-8"
          />
        </div>
        <div className="flex items-center gap-2 w-full sm:w-auto">
          <Filter className="h-4 w-4 text-muted-foreground" />
          <select
            value={filterCategory}
            onChange={(e) => setFilterCategory(e.target.value)}
            className="px-2 py-1 border border-border rounded-md bg-background text-foreground text-xs flex-1 sm:flex-none h-8"
          >
            <option value="all">All Categories</option>
            {categories.map((category) => (
              <option key={category} value={category}>
                {category.charAt(0).toUpperCase() + category.slice(1)}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="grid lg:grid-cols-5 gap-3">
        {/* Periodic Table Grid */}
        <div className="lg:col-span-3">
          <Card className="p-3">
            <CardHeader className="pb-2">
              <CardTitle className="font-serif text-lg">Periodic Table of Elements</CardTitle>
              <CardDescription className="text-xs">Organized by periods (rows) and groups (columns)</CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <div className="pb-2">
                {/* Main Periodic Table */}
                <div className="w-full">
                  {/* Group Labels */}
                  <div className="grid gap-0.5 mb-1" style={{ gridTemplateColumns: "repeat(18, minmax(35px, 1fr))" }}>
                    {Array.from({ length: 18 }, (_, i) => i + 1).map((group) => (
                      <div
                        key={`group-${group}`}
                        className="text-center text-[9px] font-semibold text-muted-foreground"
                      >
                        {group}
                      </div>
                    ))}
                  </div>

                  {/* Periodic Table Rows */}
                  {Array.from({ length: 7 }, (_, i) => i + 1).map((period) => (
                    <div
                      key={`period-${period}`}
                      className="grid gap-0.5 mb-1 items-start"
                      style={{ gridTemplateColumns: "repeat(18, minmax(35px, 1fr))" }}
                    >
                      {Array.from({ length: 18 }, (_, i) => i + 1).map((group) => {
                        const element = getElementByPosition(group, period)
                        return (
                          <div key={`${group}-${period}`}>
                            {element ? (
                              <ElementCell
                                element={element}
                                isSelected={selectedElement?.atomicNumber === element.atomicNumber}
                                onClick={() => setSelectedElement(element)}
                              />
                            ) : (
                              <div className="w-full h-10 sm:h-12 rounded bg-muted/10 border border-dashed border-muted"></div>
                            )}
                          </div>
                        )
                      })}
                    </div>
                  ))}

                  {/* Lanthanides Row */}
                  {lanthanides.length > 0 && (
                    <div className="mt-2 pt-2 border-t">
                      <div className="text-[9px] font-semibold text-muted-foreground mb-1">Lanthanides</div>
                      <div
                        className="grid gap-0.5"
                        style={{ gridTemplateColumns: "repeat(auto-fit, minmax(35px, 1fr))" }}
                      >
                        {lanthanides.map((element) => (
                          <ElementCell
                            key={element.atomicNumber}
                            element={element}
                            isSelected={selectedElement?.atomicNumber === element.atomicNumber}
                            onClick={() => setSelectedElement(element)}
                          />
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Actinides Row */}
                  {actinides.length > 0 && (
                    <div className="mt-2 pt-2 border-t">
                      <div className="text-[9px] font-semibold text-muted-foreground mb-1">Actinides</div>
                      <div
                        className="grid gap-0.5"
                        style={{ gridTemplateColumns: "repeat(auto-fit, minmax(35px, 1fr))" }}
                      >
                        {actinides.map((element) => (
                          <ElementCell
                            key={element.atomicNumber}
                            element={element}
                            isSelected={selectedElement?.atomicNumber === element.atomicNumber}
                            onClick={() => setSelectedElement(element)}
                          />
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Element Details Panel */}
        <div className="lg:col-span-2 space-y-3">
          {selectedElement ? (
            <Card className="p-3">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between gap-2">
                  <div>
                    <CardTitle className="font-serif text-base">{selectedElement.name}</CardTitle>
                    <CardDescription className="text-sm font-semibold">{selectedElement.symbol}</CardDescription>
                  </div>
                  <div
                    className={`w-12 h-12 rounded flex items-center justify-center text-white font-black text-lg flex-shrink-0 ${
                      categoryColors[selectedElement.category]?.split(" ")[0]
                    }`}
                  >
                    {selectedElement.symbol}
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-2 p-0">
                <p className="text-xs text-muted-foreground italic">{selectedElement.summary}</p>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Basic Info</h4>
                  <div className="grid grid-cols-2 gap-1 text-[10px]">
                    <div className="bg-muted p-1 rounded">
                      <div className="text-muted-foreground">Atomic #</div>
                      <div className="font-bold">{selectedElement.atomicNumber}</div>
                    </div>
                    <div className="bg-muted p-1 rounded">
                      <div className="text-muted-foreground">Mass</div>
                      <div className="font-bold">{selectedElement.atomicMass}</div>
                    </div>
                    <div className="bg-muted p-1 rounded">
                      <div className="text-muted-foreground">Group</div>
                      <div className="font-bold">{selectedElement.group}</div>
                    </div>
                    <div className="bg-muted p-1 rounded">
                      <div className="text-muted-foreground">Period</div>
                      <div className="font-bold">{selectedElement.period}</div>
                    </div>
                  </div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Category</h4>
                  <Badge className="w-full justify-center py-0 text-[10px]">
                    {selectedElement.category.toUpperCase()}
                  </Badge>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Electron Config</h4>
                  <code className="text-[9px] bg-muted px-1 py-0.5 rounded block break-words">
                    {selectedElement.electronConfiguration}
                  </code>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Phase at STP</h4>
                  <div className="text-xs text-muted-foreground">{selectedElement.phaseAtSTP}</div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Discovery</h4>
                  <div className="text-xs text-muted-foreground">
                    {selectedElement.discoveredBy} ({selectedElement.discoveryYear})
                  </div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Source</h4>
                  <div className="text-xs text-muted-foreground">{selectedElement.source}</div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Melting Point</h4>
                  <div className="text-xs text-muted-foreground">
                    {selectedElement.meltingPointC !== null ? `${selectedElement.meltingPointC}°C` : "N/A"}
                  </div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Boiling Point</h4>
                  <div className="text-xs text-muted-foreground">
                    {selectedElement.boilingPointC !== null ? `${selectedElement.boilingPointC}°C` : "N/A"}
                  </div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Density</h4>
                  <div className="text-xs text-muted-foreground">
                    {selectedElement.density !== null ? `${selectedElement.density} g/cm³` : "N/A"}
                  </div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Electronegativity</h4>
                  <div className="text-xs text-muted-foreground">
                    {selectedElement.electronegativity !== null ? `${selectedElement.electronegativity}` : "N/A"}
                  </div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-semibold text-xs">Ionization Energy</h4>
                  <div className="text-xs text-muted-foreground">
                    {selectedElement.ionizationEnergy !== null ? `${selectedElement.ionizationEnergy} kJ/mol` : "N/A"}
                  </div>
                </div>
              </CardContent>
            </Card>
          ) : (
            <Card className="p-3">
              <CardHeader className="pb-2">
                <CardTitle className="font-serif text-lg">Select an Element</CardTitle>
              </CardHeader>
              <CardContent className="text-center text-muted-foreground">
                Click on any element in the periodic table to view details.
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  )
}
